// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: LoginControllerImpl.java.vsl in andromda-bpm4struts-cartridge-coppetec.
//
package br.mdarte.exemplo.academico.accessControl;

import javax.servlet.http.HttpServletRequest;

import br.mdarte.exemplo.academico.util.Constantes;
import br.mdarte.exemplo.academico.util.CriptoUtils;
import org.apache.commons.lang.StringUtils;
import java.util.HashMap;
import java.util.Collection;

import accessControl.ControleAcesso;
import accessControl.Operador;

public class LoginControllerImpl extends LoginController
{

    public void handlePosLogin(Operador operador, HttpServletRequest request) throws Exception {
    
    }

}