// license-header java merge-point
// Generated by: SessionBeanImpl.vsl in andromda-ejb-cartridge-coppetec.
package br.mdarte.exemplo.academico.cs.curso;

import br.mdarte.exemplo.academico.util.PaginationStrategy;

/**
 * @see br.mdarte.exemplo.academico.cs.curso.CursoHandler
 */
public class CursoHandlerBeanImpl
    extends CursoHandlerBean
    implements CursoHandler, CursoHandlerLocal
{

}
