// license-header java merge-point
// Generated by: SessionBeanImpl.vsl in andromda-ejb-cartridge-coppetec.
package br.mdarte.exemplo.academico.cs.estudante;

import java.util.Collection;

import br.gov.mdarte.controleacesso.util.Util;
import br.mdarte.exemplo.academico.ServiceLocator;
import br.mdarte.exemplo.academico.action.ActionException;
import br.mdarte.exemplo.academico.cd.Estudante;
import br.mdarte.exemplo.academico.cd.EstudanteImpl;
import br.mdarte.exemplo.academico.vo.EstudanteVO;

/**
 * @see br.mdarte.exemplo.academico.cs.estudante.EstudanteHandler
 */
public class EstudanteHandlerBeanImpl extends EstudanteHandlerBean implements EstudanteHandler, EstudanteHandlerLocal
{
	@Override
	public Estudante handleMantemEstudante(EstudanteVO estudanteVO) throws EstudanteException
	{
		Estudante estudante = new EstudanteImpl();

		if(estudanteVO.getIdEstudante() != null)
		{
			estudante.setId(estudanteVO.getIdEstudante());

			Collection estudantes;
			
			try
			{
				estudantes = ServiceLocator.instance().getEstudanteHandlerBI().selectEstudante(estudante);
			}
			catch(Exception exception)
			{
				throw new EstudanteException("estudante.handle.mantem.estudante.erro", exception);
			}

			if (!Util.checkEmpty(estudantes))
			{
				estudante = (Estudante) estudantes.iterator().next();
			}
		}

		estudante.setNome(estudanteVO.getNome());

		estudante.setMatricula(estudanteVO.getMatricula());

		Collection estudantes;
		
		try
		{
			estudantes = ServiceLocator.instance().getEstudanteHandlerBI().insertOrUpdateEstudante(estudante);
		}
		catch(Exception exception)
		{
			throw new EstudanteException("estudante.handle.mantem.estudante.erro", exception);
		}

		if(Util.checkEmpty(estudantes))
		{
			throw new EstudanteException("estudante.handle.mantem.estudante.erro");
		}
		
		estudante = (Estudante) estudantes.iterator().next();

		return estudante;
	}
}
