// license-header java merge-point
// Generated by: SessionBeanImpl.vsl in andromda-ejb-cartridge-coppetec.
package br.mdarte.exemplo.academico.cs.estudante;

import br.mdarte.exemplo.academico.util.PaginationStrategy;

/**
 * @see br.mdarte.exemplo.academico.cs.estudante.EstudanteHandler
 */
public class EstudanteHandlerBeanImpl
    extends EstudanteHandlerBean
    implements EstudanteHandler, EstudanteHandlerLocal
{

}
