// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package br.mdarte.exemplo.academico.cd;

/**
 * @see br.mdarte.exemplo.academico.cd.Curso
 */
    
public class  CursoImpl     extends br.mdarte.exemplo.academico.cd.CursoAbstract  {
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = -6495172144479822107L;

    public CursoImpl()  {

    }




}
