// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
//
package br.mdarte.exemplo.academico.cd;

/**
 * @see br.mdarte.exemplo.academico.cd.Estudante
 */
    
public class  EstudanteImpl     extends br.mdarte.exemplo.academico.cd.EstudanteAbstract  {
    /** 
     * The serial version UID of this class. Needed for serialization. 
     */
    private static final long serialVersionUID = -6608100513793347408L;

    public EstudanteImpl()  {

    }




}
