// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: Util.vsl in andromda-java-cartridge-coppetec.
//
package br.mdarte.exemplo.academico.util;

import br.mdarte.exemplo.academico.util.UtilAbstract;

public class Util extends UtilAbstract{

}
