// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TransferObjectImpl.vsl in andromda-hibernate-cartridge.
//
package br.mdarte.exemplo.academico.to;

/**
br/mdarte/exemplo/academico/to/CursoTOImpl.java
 * 
 */
public  class CursoTOImpl extends CursoTO
{

    private static final long serialVersionUID = -6495172144479822107L;




}