// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TransferObjectImpl.vsl in andromda-hibernate-cartridge.
//
package br.mdarte.exemplo.academico.to;

/**
br/mdarte/exemplo/academico/to/EstudanteTOImpl.java
 * 
 */
public  class EstudanteTOImpl extends EstudanteTO
{

    private static final long serialVersionUID = -6608100513793347408L;




}